### ISSUE TITLE
APM Processing OTEL Collector Attributes to Labels Rather than Attributes

### ISSUE THREAD

**Issue by KnechtionsCoding** [elastic/apm-server#8074] opened 2022-05-09 22:16 UTC
**APM Server version** (`apm-server version`): 7.17.2

**Description of the problem including expected versus actual behavior**: 

We use open telemetry to collect traces from istio. As part of that, and in lieu of #4468 we'd like to be able upsert the `deployment.environment` variable in the open telemetry collector. We've attempted both `service.environment` and `deployment.environment`. Per the [APM Documentation](https://www.elastic.co/guide/en/apm/guide/7.17/open-telemetry.html) it should be `deployment.environment`. We've configured an attribute processor as such: 

```yaml
  # Mutate the Data
  processors:
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
    attributes:
      actions:
        - key: service.environment
          action: upsert
          value: "dev"
        - key: deployment.environment
          action: upsert
          value: "dev"
```

However, when the APM server receives it it parses it into `labels.service_environment` and `labels.deployment_environment` respectively. This is true even when using a non-string value, which according to [otel's maintainers is not allowed](https://github.com/open-telemetry/opentelemetry-specification/issues/948#issuecomment-694539451)

I do see it being set properly on the Open Telemetry collector:

```txt
Span #63
    Trace ID       : 32a7bd42c119e7883eac24a9c4527561
    Parent ID      : 461aabc5ff251158
    ID             : d8ffa6453eb48b15
    Name           : foo.bar.svc.cluster.local:80/*
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2022-05-09 22:00:31.286890085 +0000 UTC
    End time       : 2022-05-09 22:00:31.296932743 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message :
Attributes:
     -> http.url: STRING(http://foo.bar.svc.cluster.local/v1)
     -> istio.canonical_service: STRING(sonic-demo-app-publisher)
     -> zone: STRING(us-east4-b)
     -> downstream_cluster: STRING(-)
     -> istio.mesh_id: STRING(cluster.local)
     -> http.protocol: STRING(HTTP/1.1)
     -> OperationName: STRING(Egress)
     -> response_size: STRING(71)
     -> node_id: STRING(sidecar~10.17.134.74~foo.bar.svc.cluster.local)
     -> guid:x-request-id: STRING(c2df7068-2939-44f8-adb8-4182b296486a)
     -> request_size: STRING(1460)
     -> http.status_code: STRING(200)
     -> istio.canonical_revision: STRING(0.0.1)
     -> peer.address: STRING(10.17.134.74)
     -> response_flags: STRING(-)
     -> http.method: STRING(POST)
     -> user_agent: STRING(Apache-HttpClient/4.5.12 (Java/11.0.13))
     -> istio.namespace: STRING(bar)
     -> upstream_cluster.name: STRING(outbound|80||foo.bar.svc.cluster.local)
     -> upstream_cluster: STRING(outbound|80||foo.bar.svc.cluster.local)
     -> component: STRING(proxy)
     -> opencensus.same_process_as_parent_span: BOOL(false)
     -> service.environment: STRING(dev)
     -> deployment.environment: STRING(dev)
ResourceSpans #1
Resource SchemaURL:
Resource labels:
     -> service.name: STRING(foo.bar
     -> opencensus.starttime: STRING(2022-05-09T14:18:30.616783293Z)
     -> host.name: STRING(foo.bar)
     -> process.pid: INT(32)
     -> telemetry.sdk.version: STRING(0.5.0-dev)
     -> opencensus.exporterversion: STRING(0.5.0-dev)
     -> telemetry.sdk.language: STRING(cpp)
```

APM should be placing an upserted attribute from the collector properly as though it was coming from the agent.

Screenshot of json document in APM after upsert
<img width="1199" alt="Screen Shot 2022-05-09 at 6 13 37 PM" src="https://user-images.githubusercontent.com/6039922/167507496-20bcdbea-9232-47dc-8484-ccc9544c2307.png">

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Default APM configuration of 7.17.2
 2. Default Otel Collector
 3. Add processor that upserts.

**Provide logs (if relevant)**:

**Comment by marclop** [comment] 2022-05-11 07:10
@KnechtionsCoding I've been unable to reproduce this using the OTel Go client and [`sendotlp`](https://github.com/elastic/apm-server/tree/main/systemtest/cmd/sendotlp):

```
# Checked out the 7.17 branch first, ran "docker-compose up -d; make; ./apm-server -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme -E apm-server.expvar.enabled=true -e"
$ cd systemtest/cmd/sendotlp
$ export OTEL_RESOURCE_ATTRIBUTES=service.name=test,deployment.environment=dev,service.environment=dev
$ export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:8200
$ go run main.go
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:123	sending OTLP data to http://localhost:8200
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:302	exporting metric	{"metric": {"name": "float64_counter", "kind": "CounterInstrumentKind", "start_time": "2022-05-11T13:34:47+08:00", "end_time": "2022-05-11T13:34:47+08:00", "sum": 1}}
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:302	exporting metric	{"metric": {"name": "int64_histogram", "kind": "HistogramInstrumentKind", "start_time": "2022-05-11T13:34:47+08:00", "end_time": "2022-05-11T13:34:47+08:00", "boundaries": [1, 10, 100, 1000, 10000], "counts": [0, 1, 2, 3, 0, 0], "sum": 321, "count": 6}}
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:259	exporting span	{"span": {"Name":"child1","SpanContext":{"TraceID":"6b31db508906533a573e66e05066ba7a","SpanID":"5ac163346c57b47a","TraceFlags":"01","TraceState":"","Remote":false},"Parent":{"TraceID":"6b31db508906533a573e66e05066ba7a","SpanID":"d0dd4ad39e7fc9c9","TraceFlags":"01","TraceState":"","Remote":false},"SpanKind":1,"StartTime":"2022-05-11T13:34:47.82593+08:00","EndTime":"2022-05-11T13:34:47.836946625+08:00","Attributes":null,"Events":[{"Name":"an arbitrary event","Attributes":null,"DroppedAttributeCount":0,"Time":"2022-05-11T13:34:47.836944+08:00"}],"Links":null,"Status":{"Code":0,"Description":""},"DroppedAttributes":0,"DroppedEvents":0,"DroppedLinks":0,"ChildSpanCount":0,"Resource":[{"Key":"deployment.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.name","Value":{"Type":"STRING","Value":"test"}},{"Key":"telemetry.sdk.language","Value":{"Type":"STRING","Value":"go"}},{"Key":"telemetry.sdk.name","Value":{"Type":"STRING","Value":"opentelemetry"}},{"Key":"telemetry.sdk.version","Value":{"Type":"STRING","Value":"1.5.0"}}],"InstrumentationLibrary":{"Name":"sendotlp","Version":"","SchemaURL":""}}}
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:259	exporting span	{"span": {"Name":"child2","SpanContext":{"TraceID":"6b31db508906533a573e66e05066ba7a","SpanID":"5580e212d9a17e76","TraceFlags":"01","TraceState":"","Remote":false},"Parent":{"TraceID":"6b31db508906533a573e66e05066ba7a","SpanID":"d0dd4ad39e7fc9c9","TraceFlags":"01","TraceState":"","Remote":false},"SpanKind":1,"StartTime":"2022-05-11T13:34:47.847563+08:00","EndTime":"2022-05-11T13:34:47.858493166+08:00","Attributes":null,"Events":[{"Name":"exception","Attributes":[{"Key":"exception.type","Value":{"Type":"STRING","Value":"*errors.errorString"}},{"Key":"exception.message","Value":{"Type":"STRING","Value":"an exception occurred"}}],"DroppedAttributeCount":0,"Time":"2022-05-11T13:34:47.858492+08:00"}],"Links":null,"Status":{"Code":0,"Description":""},"DroppedAttributes":0,"DroppedEvents":0,"DroppedLinks":0,"ChildSpanCount":0,"Resource":[{"Key":"deployment.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.name","Value":{"Type":"STRING","Value":"test"}},{"Key":"telemetry.sdk.language","Value":{"Type":"STRING","Value":"go"}},{"Key":"telemetry.sdk.name","Value":{"Type":"STRING","Value":"opentelemetry"}},{"Key":"telemetry.sdk.version","Value":{"Type":"STRING","Value":"1.5.0"}}],"InstrumentationLibrary":{"Name":"sendotlp","Version":"","SchemaURL":""}}}
2022-05-11T13:34:47+08:00	INFO	sendotlp/main.go:259	exporting span	{"span": {"Name":"parent","SpanContext":{"TraceID":"6b31db508906533a573e66e05066ba7a","SpanID":"d0dd4ad39e7fc9c9","TraceFlags":"01","TraceState":"","Remote":false},"Parent":{"TraceID":"00000000000000000000000000000000","SpanID":"0000000000000000","TraceFlags":"00","TraceState":"","Remote":false},"SpanKind":1,"StartTime":"2022-05-11T13:34:47.825919+08:00","EndTime":"2022-05-11T13:34:47.859388667+08:00","Attributes":null,"Events":null,"Links":null,"Status":{"Code":0,"Description":""},"DroppedAttributes":0,"DroppedEvents":0,"DroppedLinks":0,"ChildSpanCount":2,"Resource":[{"Key":"deployment.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.environment","Value":{"Type":"STRING","Value":"dev"}},{"Key":"service.name","Value":{"Type":"STRING","Value":"test"}},{"Key":"telemetry.sdk.language","Value":{"Type":"STRING","Value":"go"}},{"Key":"telemetry.sdk.name","Value":{"Type":"STRING","Value":"opentelemetry"}},{"Key":"telemetry.sdk.version","Value":{"Type":"STRING","Value":"1.5.0"}}],"InstrumentationLibrary":{"Name":"sendotlp","Version":"","SchemaURL":""}}}
```

It may be specific to the OTEL Collector Attributes, I haven't tested that yet, but will test that afterwards.

**Comment by marclop** [comment] 2022-05-11 08:09
I was able to reproduce it using the Open Telemetry Collector with the following config:

`collector.yml`
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: http://localhost:8200
    tls:
      insecure: true

  logging:
    loglevel: debug

  file:
    path: ./8074.json

# Mutate the Data
processors:
  attributes:
    actions:
      - key: service.environment
        action: upsert
        value: dev
      - key: deployment.environment
        action: upsert
        value: dev
  batch:
  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes, batch]
      exporters: [otlp, logging, file]
    metrics:
      receivers: [otlp]
      processors: [attributes, batch]
      exporters: [otlp, logging, file]
```

```console
$ curl -sLO https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.50.0/otelcol_0.50.0_darwin_arm64.tar.gz
$ tar -xvzf otelcol_0.50.0_darwin_arm64.tar.gz
$ ./otelcol --config collector.ym
```

**Comment by KnechtionsCoding** [comment] 2022-05-11 11:50
@marclop does that mean if we use something like: https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/ to set a custom_tag that maps to deployment.environment apm would properly map it?

**Comment by KnechtionsCoding** [comment] 2022-05-11 16:17
@arnestorksen That does work, and I appreciate the help! Tackar! I'd still be curious to know why the resource.attributes processor is different than the attributes processor.

**Comment by marclop** [comment] 2022-05-12 00:28
@KnechtionsCoding I don't know what the resulting OTLP trace format will look like when using the Istio `custom_tags`. If they're set at the resource level, then they should be parsed, if not, then they will be treated as labels.

@arnestorksen Thanks for providing the example processor, I did test it locally and the resource attributes were mapped correctly.

**Comment by axw** [comment] 2022-05-16 10:53
> @axw is this the expected behavior? or should we take the well defined span attributes and map them accordingly as well?

It is expected. These are attributes that describe the thing (service) that produced the events (traces, metrics, ...); they're not describing the events themselves. See also https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#resources

We should probably document this.

**Comment by marclop** [comment] 2022-05-20 03:01
should we repurpose this issue as a doc issue and document the expected behavior?

**Comment by axw** [comment] 2022-05-20 07:10
@marclop I'd rather preserve the description in this issue, so I've created https://github.com/elastic/apm-server/issues/8173 to follow up on docs. As things are working as expected here, I'll close this issue.

**Closed by axw** 2022-05-20 07:10 UTC
Labels: bug

**Comment by nazarmubeen** [comment] 2023-01-23 17:01
Hi @marclop , i need to send sample custom test metric data to APM server directly. what is the better approach to do it ?

after starting collector i get below :- 
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/9826165/214102069-1e7ad07c-7d71-41cd-949a-6affe1c96dcc.png">

i am sending data from postman to this host 

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/9826165/214102268-14b8b475-3483-432a-9590-96047a57022a.png">

however still not able to visualize the data in elastic.
