### ISSUE TITLE
Document how APM Integration can be installed in air gapped environments

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7270] opened 2022-02-11 16:00 UTC
Link to [air gapped](https://www.elastic.co/guide/en/fleet/current/air-gapped.html) environments in the APM Server docs, for describing how APM Integration can be configured with a self hosted EPR or via Kibana preconfiguration API if no EPR is set up. 

For ECE this is expected to work out of the box `>= 8.1` (still needs confirmation though).

**Comment by bmorelli25** [comment] 2022-02-11 17:37
Duplicate of https://github.com/elastic/apm-server/issues/7219?

**Comment by bmorelli25** [comment] 2022-02-15 01:12
Opened https://github.com/elastic/apm-server/pull/7285 and https://github.com/elastic/observability-docs/pull/1570 to address https://github.com/elastic/apm-server/issues/7219.

As I understand it, in 8.1, no hosted EPR setup is necessary as APM will be bundled with Kibana. This allows installation via  `config/kibana.yml`. This is not documented yet, but will eventually be doc'd in the [Fleet Air gapped docs](https://www.elastic.co/guide/en/fleet/current/air-gapped.html), which we now link to (some deets are in https://github.com/elastic/kibana/issues/100413).

@simitt Are we OK to close this as a duplicate? Or do you see additional docs required on the APM side?

**Comment by simitt** [comment] 2022-02-15 15:56
Unfortunately the fix for the setup won't make it into `8.1` and instead is scheduled for `8.2`. Yes, this issue can be closed as a duplicate.

**Closed** 2022-02-15 19:02 UTC
Labels: docs, Team:Docs
