### ISSUE TITLE
[Cloud] Agent configuration does not work when upgrading to 7.5.0

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3022] opened 2019-12-10 03:16 UTC
When using APM in Elastic Cloud, upgrading from an older deployment (in my case 7.4.1) to 7.5.0, the server's agent configuration endpoint continues to return error responses:

```
{
  "error": "not a compatible Kibana version: min version 7.5.0, configured version 7.4.1"
}
```

Forcefully restarting the APM Server fixes this.

### Steps to reproduce:

1. Create a 7.4.1 deployment
2. Upgrade deployment to 7.5.0
3. Upgrade APM to 7.5.0
4. Upgrade Kibana to 7.5.0
5. `curl -H "Authorization: Bearer <secret-token>" https://<apm-server>/config/v1/agents`

**Comment by bmorelli25** [comment] 2019-12-10 03:46
To add another data point: I recently upgraded cloud and didn't run into this problem. Looking at my cloud activity, I'm not sure if it's because I was upgrading from 7.4.2, or if it's because I upgraded Kibana before APM Server.

**Comment by jalvz** [comment] 2019-12-10 10:04
This is caused by a bug in libbeat that has been backported only to 7.5:
https://github.com/elastic/beats/pull/14494

The workaround is to upgrade Kibana first, as Brandon says - but I don't think we can require the cloud team to enforce it.

Will take the liberty to close this, but feel free to reopen if other ideas come to mind.

**Comment by jalvz** [comment] 2019-12-10 11:06
_Note for self_: when upgrading apm-server to 7.5, as described in the issue, the new code should be in place already...

**Comment by axw** [comment] 2019-12-11 03:49
The underlying issue similar: the Kibana version is never refreshed, so this call to SupportsVersion will always return false if the server initially connects to an older version of Kibana:

https://github.com/elastic/apm-server/blob/6c03abc5d9bd523c6ad75dd525c1d021ba39b4c4/beater/api/config/agent/handler.go#L128

A couple of solutions come to mind:

 1. When SupportsVersion returns false, reconnect if we haven't already done so in the past N seconds, and then check again. We could wrap that logic up inside SupportsVersion

 2. Instead of checking the version first, first do the "fetch" operation, and only if it returns 404 do we need to call SupportsVersion. If SupportsVersion has previously returned false, reconnect. This is only going to be the case if the server connects to an old Kibana, which should be unusual.

I think the second approach would have a better user experience, as it will avoid delays in agent config being delivered; it only requires an additional query when Server >7.5.0 and Kibana <7.5.0.

**Comment by jalvz** [comment] 2019-12-11 07:57
Yes, im working on it

**Comment by jalvz** [comment] 2019-12-11 08:48
fwiw,  I don't think 2) works. 
Server 7.5 with Kibana 7.4 will return empty docs because versions are not compatible, but the endpoint still exists in Kibana 7.4.
I think 1) is good enough.

**Closed** 2019-12-12 10:57 UTC
Labels: [zube]: In Progress, bug, cloud
