### ISSUE TITLE
PoC: de-obfuscate Android stack traces

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9644] opened 2022-11-22 21:48 UTC
For support of the mobile APM android agent, it is crucial to support de-cyphering obfuscated stack traces. The Elastic APM solution already offers an [API for uploading sourcemaps](https://www.elastic.co/guide/en/kibana/master/rum-sourcemap-api.html) that should be reused for stack traces sent via the Android agent. 
The APM Server fetches the sourcemaps and applies them to incoming event stack traces. The internal sourcemap handling is [subject to change](https://github.com/elastic/apm-server/issues/9643), but changes won't be user facing and they are independent of this task. 

This issue focuses on implementing the logic to de-obfuscate the error stack traces by applying a sourcemap. The [specification for the ProGuard/ReTrace mapping file format](https://www.guardsquare.com/manual/tools/retrace) should be used for implementing the mapping logic. 

@LikeTheSalad will provide an example sourcemap and error event for defining the spec and testing. 

--- 

updated to provide more context and details (28/11/2022)

**Comment by axw** [comment] 2022-11-23 00:44
There is a specification for the ProGuard/ReTrace mapping file format at https://www.guardsquare.com/manual/tools/retrace (thanks @LikeTheSalad for the link)

**Comment by gbamparop** [comment] 2022-11-30 19:19
Are the mapping files expected to be stored to ES like the sourcemaps (which will be moved there for 8.7)? If so, will we need another API in Kibana?

**Comment by LikeTheSalad** [comment] 2022-12-02 08:36
Hi! I just wanted to mention here that we found the source code for Google's tool (R8 Retrace) here: https://r8.googlesource.com/r8/+/refs/heads/main/src/main/java/com/android/tools/r8/retrace/Retrace.java - In case it can help.

Also, this is the folder with the stacktrace examples: https://drive.google.com/drive/folders/1oA66ADF3kMP4JvjHTIyPbFcuXbT0FKlz?usp=sharing

**Comment by simitt** [comment] 2022-12-05 10:05
>Are the mapping files expected to be stored to ES like the sourcemaps (which will be moved there for 8.7)? If so, will we need another API in Kibana?

We are planning on reusing the existing API endpoint and using the same ES index. The one part that is unclear from my perspective at this point is whether any of the currently used fields for the sourcemap key need to change/be extended, especially the `bundle_filepath`. @LikeTheSalad @AlexanderWert have probably more knowledge here.

**Comment by AlexanderWert** [comment] 2022-12-05 10:47
@simitt From our understanding, for mobile we only need the fields `service.name` and `service.version`. We don't see a use case for `bundle_filepath`.

**Comment by kruskall** [comment] 2023-01-05 06:08
I've opened a PR at https://github.com/elastic/apm-server/pull/9980

cc @LikeTheSalad feel free to play around with it. You can add more tests and run `go test ./internal/retrace/... -v` to validate that everything is working.

Note: we probably want to wait for https://github.com/elastic/apm-server/pull/9722 to be merged before integrating the code into the sourcemap fetcher logic.

**Comment by kruskall** [comment] 2023-01-15 21:33
@LikeTheSalad That was a fun one!

Our mapper is strictly remapping the stacktrace without changing the format. What is happening in "use case 3" is the following (I'll use a single line as example since the issue is the same for each one):

`obfuscated-crash.txt`: `<space><tab><obfuscated-line>`
APM mapper: `<space><tab><deobfuscated-line>`
`deobfuscated-crash.txt`: `<8-spaces><deobfuscated-line>`

I don't know if the spaces/tabs issue in `obfuscated-crash.txt` is due to an editor but we probably want to keep the format used in the obfuscated stacktrace when remapping it.

**Comment by LikeTheSalad** [comment] 2023-01-16 06:45
I see! Thanks for taking the time! Yeah I agree, I think we should keep the original stacktrace format, I think the spaces came from Intellij's terminal so we shouldn't worry about it.

Cheers!

**Closed** 2023-02-08 07:38 UTC
