### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by linydquantil** [elastic/apm-server#3429] opened 2020-03-05 03:06 UTC
my os version: centos 7.4
![image](https://user-images.githubusercontent.com/37830766/75943842-1fa05b00-5ed1-11ea-9fde-dae4eec14787.png)
![image](https://user-images.githubusercontent.com/37830766/75943855-2a5af000-5ed1-11ea-94ad-310e995a7b5c.png)
and i run : docker-compose up --build
![image](https://user-images.githubusercontent.com/37830766/75943912-49f21880-5ed1-11ea-8197-6d833763a4d2.png)

**Comment by axw** [comment] 2020-03-05 03:24
You can try running `make docker-compose.override.yml` first, which will set the UID used within Docker to your current user. This should fix up the "permission denied" error.

In case you're not aware, the docker-compose.yml in the apm-server repo is really meant for development. If you're looking to run the Elastic Stack along with APM Server, you might want to try https://github.com/elastic/apm-integration-testing instead.

**Comment by axw** [comment] 2020-03-06 01:12
Closing this now, since there's no confirmed bug. If you're still having issues, please open a topic in the forum, with a description of what you're trying to achieve: https://discuss.elastic.co/c/apm.

**Closed by axw** 2020-03-06 01:12 UTC
