### ISSUE TITLE
systemd causes always logging to stdout

### ISSUE THREAD

**Issue by 111andre111** [elastic/apm-server#2163] opened 2019-05-03 07:52 UTC
By default, the apm-server systemd file in 7.0.0 as well as 7.0.1 is adding the -e option. This causes that configuration in apm-server.yml around
logging.to_files: true
is not possible at the moment, because no log files will be written.
I have tested under both, Redhat and Ubuntu.

I've temporarily changed the value in the systemd file
/etc/systemd/system/multi-user.target.wants/apm-server.service
from
```
Environment="BEAT_LOG_OPTS=-e"
```
to
```
Environment="BEAT_LOG_OPTS="
```

This didn't break in the tests any functionality.
Without configuration of logging.to_files it just landed in
``` 
journalctl -f -u apm-server
```
and with configuration of logging.to_files: true the logfile was normally written under
/var/log/apm-server
or wherever you configure the destination path.

I found that there was a decision for adding the -e parameter here:
https://github.com/elastic/beats/pull/8942
https://github.com/elastic/apm-server/blob/master/changelogs/7.0.asciidoc#apm-server-version-700-alpha2
but it should be taken into consideration that it did break the to_files possibility.

**Comment by simitt** [comment] 2019-05-03 11:24
Thank you for the report! Have you seen the [documentation for logging with systemd](https://www.elastic.co/guide/en/apm/server/current/running-with-systemd.html)?

It has a [detailed explanation](https://www.elastic.co/guide/en/apm/server/current/running-with-systemd.html#_customize_systemd_unit_for_apm_server) on how to customize logging with systemd, by using the _BEAT_LOG_OPTS_ parameter. 
It looks like that's exactly what you used to change the default behaviour. You also mention you didn't run into any issues with that change. Therefore, unless there is anything else that I am missing, I suggest to close this issue, as you are describing expected behaviour.

**Comment by 111andre111** [comment] 2019-05-03 11:37
Ok, that's a good point. Thank you for pointing this out. Interesting approach. Good to know.

**Comment by simitt** [comment] 2019-05-22 06:18
Thanks again for bringing this up. The behavior is inherited from libbeat though. You're very welcome to open an enhancement issue in beats for further discussions. I am going to close this one, as it is expected behavior and changes would need to be applied in libbeat first.

**Closed by simitt** 2019-05-22 06:18 UTC
Labels: [zube]: In Progress
