### ISSUE TITLE
apm-server can't start

### ISSUE THREAD

**Issue by raly** [elastic/apm-server#2496] opened 2019-07-25 10:37 UTC
#### centos apm-server can't start

[root@user /data]# sudo service apm-server start
Starting apm-server (via systemctl):                       [  OK  ]
[root@user /data]# service apm-server status
* apm-server.service - Elastic APM Server
   Loaded: loaded (/usr/lib/systemd/system/apm-server.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2019-07-25 18:46:53 CST; 811ms ago
     Docs: https://www.elastic.co/solutions/apm
  Process: 21441 ExecStart=/usr/share/apm-server/bin/apm-server $BEAT_LOG_OPTS $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 21441 (code=exited, status=0/SUCCESS)

Jul 25 18:46:53 user.site systemd[1]: apm-server.service holdoff time over, scheduling restart.
Jul 25 18:46:53 user.site systemd[1]: start request repeated too quickly for apm-server.service
Jul 25 18:46:53 user.site systemd[1]: Failed to start Elastic APM Server.
Jul 25 18:46:53 user.site systemd[1]: Unit apm-server.service entered failed state.
Jul 25 18:46:53 user.site systemd[1]: apm-server.service failed.

**Comment by graphaelli** [comment] 2019-07-25 14:18
Thanks for reporting @raly, what linux distribution and apm-server version is this?  If 7.0.0, this might be a duplicate of #2096 and the solution is to use a [newer release](https://www.elastic.co/downloads/apm).

**Comment by oladon** [comment] 2019-07-31 20:33
I'm experiencing this (minus the errors; not seeing any of those) when upgrading to 6.8.1 or 6.8.2 from 6.7.1. Running Amazon Linux 2018.03 (CentOS-based).

Output after upgrading to 6.8.2:

```
$ sudo service apm-server status
apm-server-god is stopped
$ sudo service apm-server start
Starting apm-server: 2019-07-31T20:18:21.404Z   INFO    instance/beat.go:611    Home path: [/usr/share/apm-server] Config path: [/etc/apm-server] Data path: [/var/lib/apm-server] Logs path: [/var/log/apm-server]
2019-07-31T20:18:21.404Z        DEBUG   [beat]  instance/beat.go:648    Beat metadata path: /var/lib/apm-server/meta.json
2019-07-31T20:18:21.404Z        INFO    instance/beat.go:618    Beat UUID: 81ec4b32-81ed-464e-b9e4-940b11c80ac1
2019-07-31T20:18:21.404Z        INFO    [beat]  instance/beat.go:931    Beat info       {"system_info": {"beat": {"path": {"config": "/etc/apm-server", "data": "/var/lib/apm-server", "home": "/usr/share/apm-server", "logs": "/var/log/apm-server"}, "type": "apm-server", "uuid": "81ec4b32-81ed-464e-b9e4-940b11c80ac1"}}}
2019-07-31T20:18:21.404Z        INFO    [beat]  instance/beat.go:940    Build info      {"system_info": {"build": {"commit": "6f52d242b51fa2447b5e49b03a041570d3031359", "libbeat": "6.8.2", "time": "2019-07-24T14:18:25.000Z", "version": "6.8.2"}}}
2019-07-31T20:18:21.404Z        INFO    [beat]  instance/beat.go:943    Go runtime info {"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":2,"version":"go1.10.8"}}}
2019-07-31T20:18:21.405Z        INFO    [beat]  instance/beat.go:947    Host info       {"system_info": {"host": {"architecture":"x86_64","boot_time":"2019-07-18T19:07:52Z","containerized":false,"name":"ip-[redacted]","ip":["127.0.0.1/8","[redacted]"],"kernel_version":"4.14.77-70.59.amzn1.x86_64","mac":["[redacted]"],"os":{"family":"redhat","platform":"amzn","name":"Amazon Linux AMI","version":"2018.03","major":2018,"minor":3,"patch":0},"timezone":"UTC","timezone_offset_sec":0}}}
2019-07-31T20:18:21.405Z        INFO    [beat]  instance/beat.go:976    Process info    {"system_info": {"process": {"capabilities": {"inheritable":null,"permitted":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"effective":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"bounding":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"ambient":null}, "cwd": "/", "exe": "/usr/share/apm-server/bin/apm-server", "name": "apm-server", "pid": 10834, "ppid": 10833, "seccomp": {"mode":"disabled","no_new_privs":false}, "start_time": "2019-07-31T20:18:20.630Z"}}}
2019-07-31T20:18:21.405Z        INFO    instance/beat.go:280    Setup Beat: apm-server; Version: 6.8.2
2019-07-31T20:18:21.405Z        DEBUG   [beat]  instance/beat.go:301    Initializing output plugins
2019-07-31T20:18:21.405Z        DEBUG   [processors]    processors/processor.go:66      Processors:
2019-07-31T20:18:21.405Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.405Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.406Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.406Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.406Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.406Z        DEBUG   [processors]    conditions/conditions.go:93     New condition contains: map[]
2019-07-31T20:18:21.406Z        INFO    elasticsearch/client.go:164     Elasticsearch url: http://localhost:9200
2019-07-31T20:18:21.406Z        DEBUG   [publish]       pipeline/consumer.go:137        start pipeline event consumer
2019-07-31T20:18:21.406Z        INFO    [publisher]     pipeline/module.go:110  Beat name: ip-10-0-4-32
2019-07-31T20:18:21.407Z        INFO    [beater]        beater/beater.go:112    No pipeline callback registered
Config OK
                                                           [  OK  ]
$ sudo service apm-server status
apm-server-god is stopped
```

Nothing unusual in /var/log/apm-server/apm-server — last few lines are:

```
2019-07-31T20:15:24.762Z        INFO    [server]        beater/server.go:77     Listening on: 0.0.0.0:8200
2019-07-31T20:15:24.762Z        INFO    [server]        beater/server.go:82     RUM endpoints disabled.
2019-07-31T20:15:24.762Z        INFO    [server]        beater/server.go:91     SSL enabled.
```

Downgrading back to 6.7.1 fixes the issue, though I'm not sure if there will be complications from ELK's version not matching APM's.

Happy to open this as a separate issue if you like, too, but it seemed similar enough to the OP to report it here.

**Comment by graphaelli** [comment] 2019-08-13 20:06
@oladon Sorry about the delay, that does indeed look related.  Can you provide the steps used to install and upgrade, and any configuration you're able to share?  I did the following on centos 7 using the stock configuration both with and without systemd (looks like you're without) and was unable to reproduce but have yet to try on Amazon Linux 2018.03.

```
rpm -ivh https://artifacts.elastic.co/downloads/apm-server/apm-server-6.7.1-x86_64.rpm
service apm-server start
```

```
service apm-server status
apm-server-god (pid  119) is running...
# also verified data is ingested
```

```
rpm -Uvh https://artifacts.elastic.co/downloads/apm-server/apm-server-6.8.2-x86_64.rpm
service apm-server restart
```

```
service apm-server status
apm-server-god (pid  230) is running...
# also verified data is still ingested
```

**Comment by oladon** [comment] 2019-08-14 15:22
@graphaelli Standard yum install from the Elastic repo:

```
$ cat /etc/yum.repos.d/elastic.repo
[elasticsearch-6.x]
name=Elasticsearch repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
```

```
$ yum info apm-server
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
Name        : apm-server
Arch        : x86_64
Version     : 6.7.1
Release     : 1
Size        : 37 M
Repo        : installed
From repo   : elasticsearch-6.x
Summary     : Elastic APM Server
URL         : https://www.elastic.co/solutions/apm
License     : Elastic-License
Description : Elastic APM Server
```

I will note that this box is also running a full ELK+Wazuh stack, but that's never caused any issues for APM before. Downgrading does seem to have solved it with no negative complications from the version not matching that of ELK.

**Comment by graphaelli** [comment] 2019-08-15 17:22
Thanks @oladon.  I've tried to reproduce on a stock centos 7 using the yum repo without success - still to try on Amazon Linux 2018.03.  I wouldn't expect any issues with using mixed minors of elasticsearch and apm-server (they would be a bug), except that you may be missing some newer features.

Are you able to turn on debug logging `logging.level: debug` to help troubleshoot further?

**Comment by oladon** [comment] 2019-08-15 18:05
@graphaelli I believe that first snippet is actually with debug logging on — unless you're referring to some other debug logging?

I may be able to find some time to play around with it in our pre-production environment in the next few weeks... will report back if I'm able to find the time and reproduce it there.

**Comment by graphaelli** [comment] 2019-08-15 18:07
Ah it sure is, I don't suppose you have any logging selectors set?  I was hoping to see something related to shutdown, like:

```
DEBUG	[elasticsearch]	elasticsearch/client.go:347	PublishEvents: 1 events have been published to elasticsearch in 530.917762ms.
DEBUG	[publisher]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 1]
DEBUG	[publisher]	memqueue/eventloop.go:535	broker ACK events: count=1, start-seq=1, end-seq=1
DEBUG	[publisher]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:1
DEBUG	[publisher]	memqueue/ackloop.go:131	ackloop:  done send ack
DEBUG	[service]	service/service.go:53	Received sigterm/sigint, stopping
INFO	[beater]	beater/beater.go:342	stopping apm-server... waiting maximum of 5 seconds for queues to drain
INFO	[beater]	beater/beater.go:227	Server stopped
DEBUG	[publisher]	pipeline/client.go:149	client: closing acker
DEBUG	[publisher]	pipeline/client.go:151	client: done closing acker
DEBUG	[publisher]	pipeline/client.go:155	client: cancelled 0 events
```

**Comment by oladon** [comment] 2019-08-15 18:16
No selectors. Here's the logging section of the configuration file (with the log level set back to warning now that we've reverted versions):

```
#================================ Logging ======================================
#
# There are three options for the log output: syslog, file, stderr.
# Under Windows systems, the log files are per default sent to the file output,
# under all other system per default to syslog.

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: warning

# Enable debug output for selected components. To enable all selectors use ["*"]
# Other available selectors are "beat", "publish", "service"
# Multiple selectors can be chained.
#logging.selectors: [ ]

# Send all logging output to syslog. The default is false.
#logging.to_syslog: true

# If enabled, apm-server periodically logs its internal metrics that have changed
# in the last period. For each metric that changed, the delta from the value at
# the beginning of the period is logged. Also, the total values for
# all non-zero internal metrics are logged on shutdown. The default is true.
#logging.metrics.enabled: false

# The period after which to log the internal metrics. The default is 30s.
#logging.metrics.period: 30s

# Logging to rotating files. Set logging.to_files to false to disable logging to
# files.
logging.to_files: true
logging.files:
  # Configure the path where the logs are written. The default is the logs directory
  # under the home path (the binary location).
  path: /var/log/apm-server

  # The name of the files where the logs are written to.
  name: apm-server

  # Configure log file size limit. If limit is reached, log file will be
  # automatically rotated
  rotateeverybytes: 10485760 # = 10MB

  # Number of rotated log files to keep. Oldest files will be deleted first.
  keepfiles: 7

  # The permissions mask to apply when rotating log files. The default value is 0600.
  # Must be a valid Unix-style file permissions mask expressed in octal notation.
  permissions: 0600

# Set to true to log messages in json format.
#logging.json: false
```

I believe these are 99–100% default.

**Comment by graphaelli** [comment] 2019-08-16 17:39
Agreed, I don't expect the minimal changes there to be responsible.  I just tried on an Amazon Linux 2018.03.20190611 image and still could not reproduce.  If you are able to find time to dig up more details I'd be happy to dig in further.

**Comment by philippkahr** [comment] 2019-10-25 19:14
Hi,

I run into the same problem and I was able to build a reproducible box :).

You need to have `vagrant`, `virtualbox` and `ansible` on your machine. If you are using a mac you can easily install those with `brew cask install virtualbox ansible vagrant`

change in a shell to the `/` directory and do:
1. `vagrant up`
1.1 You will see that it install `vim` and `nano` into the centos7 box. 
1.2 It will copy the apm-server.rpm version 7.4.1 from `roles/APM/files` to a directory inside the box. 1.3 Then it will run `yum install path-to-apm.rpm`. 
1.4. It will template the configuration file from `roles/apm/templates` to `/etc/apm-server/apm-server.yml`
1.5 It will enable the systemd service
1.6 It will restart the systemd service
2. `vagrant ssh`
2.1. now you are inside the box and are able to browse around like you are on a normal Linux.
2.2. you have to do `sudo su` to do anything.
2.3. now run `systemctl status apm-server` you will see it `failed`.
2.4. now run `apm-server -e` and it will work perfectly.
3. If you want to change the `apm-server.yml` you can easily just copy the contents from your `apm-server.yml` to the `apm-server.j2`.
3.1 then run `vagrant provision` (it will rerun all the ansible steps and restart the service and so on)
4. if you are done, run `vagrant destroy` this will destroy the virtualbox.

Here is the link to the repository. https://github.com/philippkahr/issue-with-apm I also linked this issue to the commit. I hope it helps in solving this issue. If you run into any issues with my vagrant build, just ask :).

**Comment by graphaelli** [comment] 2019-10-25 20:30
Thanks for the detailed reproduction.  I tried it out and see:

```
journalctl -t apm-server
-- Logs begin at Fri 2019-10-25 19:58:43 UTC, end at Fri 2019-10-25 20:24:11 UTC. --
Oct 25 20:24:10 localhost.localdomain apm-server[27733]: Exiting: error loading config file: config file ("/etc/apm-server/apm-server.yml") must be owned by the user identifier (uid=499) or root
```

Following `chown apm-server:apm-server /etc/apm-server/apm-server.yml` apm-server was able to start.  I believe https://github.com/philippkahr/issue-with-apm/pull/1 should do the same.

**Comment by philippkahr** [comment] 2019-10-25 21:10
Hi @graphaelli 

thanks for spotting this one. I am confused about why this is happening, maybe something in the RPM install does that? But ansible would still reset the permission to root:root. So if I run my ansible, with `root:root` as owner my `ls -lisa` looks like this:

```
[root@itsm-test-host-1 vagrant]# ls -lisa /etc/apm-server/apm-server.yml 
34130560 4 -rw-------. 1 root root 1825 Oct 25 20:54 /etc/apm-server/apm-server.yml
```

What confuses me is that the error messages state `by the user identifier (uid=499) or root`. It is owned by root? Still starting apm-server is not working with systemd. 

```
Oct 25 20:56:47 itsm-test-host-1 apm-server[7813]: Exiting: error loading config file: open /etc/apm-server/apm-server.yml: permission denied
```

I think that is still an issue, I do not know how to fix it universally. Something inside the `init.d` script? I cannot find any `systemd` related file inside `/etc/systemd/system/`. Inside the `init.d` file there is this statement: `beat_user="${BEAT_USER:-apm-server}"` maybe that is the issue? I am not an `init.d` expert, I mainly work with systemd files. Metric, file, packet and auditbeat work without any issue in this vagrantbox, even when set to `root:root`. So why does the apm-server break, when set to `root:root`?

Changing it to `chown apm-server:apm-server /etc/apm-server/apm-server.yml` does the trick. Thanks for the PR!

**Ressources**
https://github.com/elastic/apm-server/issues/2721

<https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html>

**Comment by oladon** [comment] 2019-10-25 21:34
Sweet, now I don't have to feel bad about not having gotten back around to this — thanks @philippkahr! :)

**Comment by graphaelli** [comment] 2019-10-28 13:59
@philippkahr I'm glad you're up and running now.  

Regarding the final issue you ran into - apm-server will only start up if the configuration is owned by the user running the process as root, as I'm sure you've noticed.  The two scenarios we've run into there are:

1.  running as apm-server under systemd (the default) with config ownership set to `root:root` - apm-server will start as long as it can read the config (in practice, world readable, not recommeded)

2. running as root under systemd with config ownership set to `root:root`.

The 2nd scenario is what you're running into here:

> changing back to chown apm-server:apm-server /etc/apm-server/apm-server.yml and doing systemctl restart apm-server leads to:

```
Oct 25 21:29:50 itsm-test-host-1 apm-server[6199]: Exiting: error loading config file: config file ("/etc/apm-server/apm-server.yml") must be owned by the user identifier (uid=0) or root
```

When running as root, the file ownership must be root as well.  Compare that with a misconfigured scenario 1:

```
Oct 25 20:24:10 localhost.localdomain apm-server[27733]: Exiting: error loading config file: config file ("/etc/apm-server/apm-server.yml") must be owned by the user identifier (uid=499) or root
```

where the file may be owned by either the process owner (`uid 499` - `apm-server`) or root.

Most beats necessarily run as root so don't run into this issue but apm-server doesn't have the same requirements so it runs with lower privileges by default.

**Comment by philippkahr** [comment] 2019-10-28 16:43
@graphaelli 

Hi, thanks for clearing this one up. I was a bit confused about the error and log messages, to be honest. Maybe we should point out to the folks that it always has to be `apm-server:apm-server` somewhere here: <https://www.elastic.co/guide/en/apm/server/7.4/configuring-howto-apm-server.html> ?

**Comment by graphaelli** [comment] 2019-10-28 17:26
Great idea, opened #2865 to track that and closing this one out.

**Closed by graphaelli** 2019-10-28 17:26 UTC
Labels: [zube]: Blocked

**Comment by oladon** [comment] 2019-10-28 17:44
Isn't there still an issue to be resolved, in that the package should be installed correctly (with the correct permissions) by yum?

**Comment by philippkahr** [comment] 2019-10-28 22:40
Hi @oladon 

```console
cd ~/Downloads
vagrant init hbsmith/awslinux
vagrant up
vagrant ssh
wget https://artifacts.elastic.co/downloads/apm-server/apm-server-7.4.1-x86_64.rpm
sudo yum -y install apm-server-7.4.1-x86_64.rpm
```
```console
ls -lisa /etc/apm-server/
total 164
394472   4 drwxr-xr-x  2 root       root         4096 Oct 28 22:39 .
393218   4 drwxr-xr-x 80 root       root         4096 Oct 28 22:39 ..
394474  40 -rw-------  1 apm-server apm-server  36910 Oct 22 15:22 apm-server.yml
403819 116 -rw-r--r--  1 root       root       116996 Oct 22 15:22 fields.yml
```

seems to be set correctly. I do not have any AWS access to test it quickly, but I found this vagrant box.

**Comment by bmorelli25** [comment] 2019-12-10 19:27
> Hi, thanks for clearing this one up. I was a bit confused about the error and log messages, to be honest. Maybe we should point out to the folks that it always has to be apm-server:apm-server somewhere here: https://www.elastic.co/guide/en/apm/server/7.4/configuring-howto-apm-server.html ?

@philippkahr, I've opened a documentation PR to address this: https://github.com/elastic/apm-server/issues/2865. If you have time, any feedback is welcome.

**Comment by Big-al** [comment] 2020-11-05 22:25
I had this same issue again in APM v 7.7.1 

On an Ubuntu server 18.04 I ran `sudo apm-server setup`
This gave me the error:
`Exiting: error loading config file: config file ("/etc/apm-server/apm-server.yml") must be owned by the us                                      er identifier (uid=0) or root`

I then ran `sudo -u apm-server apm-server test config` to verify the config, which resultet in `Config OK` .

As the error suggests, i changed ownership of the config file to root with:
`sudo chown root /etc/apm-server/apm-server.yml`

Then running the setup command again resulted in:
Index setup finished.
Loaded Ingest pipelines

As expected.
