### ISSUE TITLE
APM Server 8.16 test plan

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#14405] opened 2024-10-21 14:23 UTC
# Manual Test Plan

List of changes: https://github.com/elastic/apm-server/compare/8.15...8.16

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## go-docappender library

- [x] https://github.com/elastic/go-docappender/pull/189 [N/A]
 
## apm-data library

- [x] https://github.com/elastic/apm-data/pull/341  [@inge4pres]
- [x] https://github.com/elastic/apm-data/pull/358  [N/A]
- [x] https://github.com/elastic/apm-data/pull/359 [N/A]

## opentelemetry-lib library

- [x] https://github.com/elastic/opentelemetry-lib/pull/90 [@inge4pres ]

## Test cases from the GitHub board

- [x]  https://github.com/elastic/apm-server/pull/13523 [@endorama ]
- [x]  https://github.com/elastic/apm-server/pull/13809 [@marclop ]
- [x]  https://github.com/elastic/apm-server/pull/14350 [@1pkg ]
- [x]  https://github.com/elastic/apm-server/pull/14362 [@rubvs ] 
- [x]  https://github.com/elastic/apm-server/pull/14404 [@kruskall ]
- [x]  https://github.com/elastic/apm-server/pull/14231 [@lahsivjar ]

**Comment by simitt** [comment] 2024-10-22 06:21
@kruskall IMO we do not need to test the changes in the `opentelemetry-lib`; confirmed by @lahsivjar 
> in the test plan, only [https://github.com/elastic/opentelemetry-lib/pull/90](https://www.google.com/url?q=https://github.com/elastic/opentelemetry-lib/pull/90&sa=D&source=docs&ust=1729581577407387&usg=AOvVaw3xpz2-nxfOTX9pm2uOq70p) is needed to be tested if it hasn't already been tested in the testathon.

**Comment by marclop** [comment] 2024-10-24 04:25
Marked https://github.com/elastic/go-docappender/pull/189 as done since it doesn't need to be tested. `DynamicTemplates` is only exposed in `BulkIndexer`. APM Server doesn't use this newly added field, nor does the `Appender` by default.

Marked https://github.com/elastic/apm-data/pull/358 and https://github.com/elastic/apm-data/pull/359 as done since I don't think they  need any manual testing.

**Comment by endorama** [comment] 2024-10-24 14:48
I added a unit test for the behavior changes around retry in https://github.com/elastic/apm-server/pull/13523. PR here: https://github.com/elastic/apm-server/pull/14433

Does this suffice for considering it done for the test plan?

**Comment by 1pkg** [comment] 2024-10-24 21:57
Similar to above, I had to add an additional concurrent auto test for #14335 in PR here #14443 since it's hard to reproduce manually.

**Comment by rubvs** [comment] 2024-10-29 16:53
Was able to reproduce https://github.com/elastic/apm-server/pull/14339 via the comments in https://github.com/elastic/apm-server/issues/14337. However, to see the double in `gc ticks`, I had to replace `time.Sleep(time.Minute)` with an uneven count like `time.Sleep(5*time.Second)`

**Comment by lahsivjar** [comment] 2024-10-29 23:19
Successfully tested https://github.com/elastic/apm-server/pull/14231, details [here](https://github.com/elastic/apm-server/pull/14231#issuecomment-2445497056).

**Comment by inge4pres** [comment] 2024-10-30 16:23
Tested https://github.com/elastic/opentelemetry-lib/pull/90 with https://github.com/elastic/opentelemetry-lib/pull/90#issuecomment-2447709262

**Comment by endorama** [comment] 2024-10-30 18:25
PR https://github.com/elastic/apm-server/pull/14433 merged, marking 429 changes tested.

**Closed as completed** 2024-11-01 00:41 UTC
Labels: test-plan
