### ISSUE TITLE
Cloud Fleet APM gives non consistent central config data

### ISSUE THREAD

**Issue by fuzolan** [elastic/apm-server#7507] opened 2022-03-09 16:12 UTC
When I setup any central settings via apm settings menu.
I can also see the policies when I go to my "Elastic Cloud agent Policy" under Agent polcies and click "View Policies"
When I lookup those values via REST then I get not those results back.

https://xxx.apm.westeurope.azure.elastic-cloud.com/config/v1/agents?service.name=xxx&service.environment=xxx

It give me different results. It does not matter if I wait hours or restart the APM/Fleet. Recreate those settings are also not working.

I'm using 7.17.1

**Comment by simitt** [comment] 2022-03-21 18:03
Hi @fuzolan , apologies for the late response. I was not able to reproduce this with an ESS APM deployment `7.17.1` where I switched to managed APM Server. Can you please share more details on what you are seeing configured in 
* the APM app
* the cloud agent policy
* the REST command

For example, I am seeing the following: 
* APM app
<img width="1528" alt="Screenshot 2022-03-21 at 18 59 54" src="https://user-images.githubusercontent.com/5555349/159335764-05219bc5-5031-413d-9a95-1cebc7c63b8a.png">

* the cloud agent policy
<img width="479" alt="Screenshot 2022-03-21 at 19 00 22" src="https://user-images.githubusercontent.com/5555349/159335835-455b1082-0d17-4975-87cd-68969cac4a49.png">

* the REST command
```
curl -i -k -H "Authorization: Bearer ${ELASTIC_APM_SECRET_TOKEN}"  "https://xxx.apm.us-central1.gcp.cloud.es.io/config/v1/agents?service.name=service1&service.environment=production"
HTTP/2 200
access-control-expose-headers: Etag
cache-control: max-age=30, must-revalidate
content-type: application/json
date: Mon, 21 Mar 2022 18:00:28 GMT
etag: "d904d588b97b8997ef6d737cfdeb037cfad4a424"
x-cloud-request-id: jA1AWnPaS6iQALFLIyxvlQ
x-content-type-options: nosniff
x-found-handling-cluster: e48bf493263242a299294a6ad8bcff1c
x-found-handling-instance: instance-0000000001
content-length: 128

{
  "api_request_size": "23mb",
  "api_request_time": "600ms",
  "capture_body": "errors",
  "transaction_sample_rate": "0.9"
}
```

**Comment by simitt** [comment] 2022-04-04 08:39
Since I wasn't able to reproduce and there was no further update on the setup in which this occured, closing the issue. @fuzolan in case you still experience issues, please head over to the [Elastic APM discuss forum](https://discuss.elastic.co/c/observability/apm/58) and open an entry there, as we generally want to keep github issues for confirmed bugs and enhancement requests.

**Closed by simitt** 2022-04-04 08:39 UTC
Labels: bug
