### ISSUE TITLE
How to handle partial transactions in intake v2?

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1241] opened 2018-08-01 11:16 UTC
Is it problematic if spans are missing for transactions? 
If so can we detect missing spans server side and log or report them anywhere? What should the behaviour be if missing spans are detected?
Figure out a solution together with @elastic/apm-ui .

**Comment by sqren** [comment] 2018-08-01 11:25
If the transaction can somehow contain the number of spans it has (eg. `transaction.spanCount.total`), the UI can correlate this number with the number of spans currently available. If they don't match we show a warning to the user.

**Comment by watson** [comment] 2018-08-01 11:32
With the v2 api I don't think it's possible to detect by the APM Server, as the spans always are sent to the server before the transaction is. So you don't know if the missing transaction is just missing because the agent hasn't sent it yet or because it's lost.

This will be the norm when looking at the newest data, so the UI just need to gracefully handle it when a transaction is missing.

**Comment by jalvz** [comment] 2018-08-01 11:33
No idea of how this all plays together, but can it happen that with DT, a user might click on a span to eg. see a trace on an upstream service, so you have to lookup by `span.parent_id` or similar, and it is not found because it is missing?

**Comment by simitt** [comment] 2018-08-23 12:15
@jalvz every `span` and `transaction` also have a `trace_id` as required field with distributed tracing. 

@elastic/apm-agent-devs is it possible to send a `transaction.spanCount.total` as proposed by @sqren ?

It could also happen that a `transaction` is missing, but `spans` are sent. How would we show this?

**Comment by sqren** [comment] 2018-08-23 13:07
> It could also happen that a transaction is missing, but spans are sent. How would we show this?

Will the transaction eventually show up (and how long will that take) or can the transaction be permanently lost?

Today I don't think there is any way to view spans, if the transaction is missing, so the problem can't exist. 
With distributed tracing it _could_ happen. I'm okay with just showing the spans, and not the transaction, if the problem is only temporary (few minutes).

**Comment by simitt** [comment] 2018-08-23 16:17
With v2 it could definitely happen that a transaction is permanently missing. 
E.g. Internal Server queue was full, transaction was dropped, but spans are stored.

**Comment by formgeist** [comment] 2018-08-23 17:42
I'm not sure I fully understand what happens in V2. Is it possible we can have a zoom about tomorrow?

**Comment by felixbarny** [comment] 2018-08-24 07:09
> @elastic/apm-agent-devs is it possible to send a transaction.spanCount.total as proposed by @sqren ?

that should be possible

**Comment by watson** [comment] 2018-08-24 07:50
FYI: There's a long running discussion this in the v2 protocol design proposal

**Comment by jahtalab** [comment] 2018-08-24 08:50
The RUM agent is not affected by this since we have decided to send all spans for a given transaction in the same request (due to timestamp issue)! 
So I would make `transaction.span_count.total` optional and use it in the UI only if available!

It is not a big problem to send `transaction.span_count.total` for the RUM agent as well. But I would rather not send an attribute which doesn't play any function for a particular agent.

**Comment by felixbarny** [comment] 2018-08-24 09:04
+1 for making it optional, for backwards compatibility

**Comment by simitt** [comment] 2018-08-24 09:29
@jahtalab even if you ensure to send transaction + spans in the same http request, the server might only process parts of the http request. It could still happen that some spans are missing in ES eventually. Thus the counter could also be useful for RUM.

@felixbarny if we agree agents will always send the information we can make it **required** for v2, as this hasn't been released yet.

**Comment by jahtalab** [comment] 2018-08-24 09:37
@simitt , What are the possible scenarios that a partial process of a request could happen?

**Comment by Qard** [comment] 2018-09-04 18:04
Would it be required on an unsampled transaction?

**Comment by simitt** [comment] 2018-09-05 06:46
If we make it a required attribute - yes. We can also decide to introduce `transaction.span_count.total` as an optional field, but then we cannot make any guarantees for the UI.

**Comment by felixbarny** [comment] 2018-09-05 07:03
I think that's a good point for making it optional. The UI should also not rely too much on the presence of this field and consider it optional. For example, if we want to accept other formats, like the Zipkin format someday, those will most likely not have the total span count set.

**Comment by roncohen** [comment] 2018-09-05 13:56
> Would it be required on an unsampled transaction?

Is it a hassle to include it for unsampled transactions?

We can alway relax the requirement if we suddenly want to support Zipkin formattet data. I don't think that should be an argument for making it optional now. If it's optional now, it would be difficult to make it required down the line. As @simitt  said, there's no "backwards compatibility" argument either because we're only changing it for v2. 

The comments in the issue made it clear that all agents are planning to implement it (@jahtalab said he's fine to do it, even if it _might_ not be strictly necessary for the RUM scenario), so I don't see why we shouldn't make it a requirement now - but maybe I missed something.

[@simitt's current implementation](https://github.com/elastic/apm-server/pull/1351) makes it required in v2 for all (sampled+unsampled) transactions.

**Comment by Qard** [comment] 2018-09-05 19:55
`transaction.span_count` is currently optional, for use of the `dropped` field. Making `transaction.span_count.total` required would change `transaction.span_count` from optional to required.

**Comment by roncohen** [comment] 2018-09-06 08:55
@Qard true. Is that problematic? Keep in mind We're only talking about changing things for v2. V1 stays the same.

**Comment by Qard** [comment] 2018-09-06 16:06
Nope, just pointing out we are already discussing changing from optional to required, so it wouldn't be a _change_ to make it optional, it'd just be deferring the requirement until later. I'm good with requiring it now though.

I just wanted to verify that "required" meant an unsampled transaction should have `transaction.span_count.total` of `0`, which changes from the existing behavior of not including `span_count` at all, on an unsampled transaction.

**Comment by roncohen** [comment] 2018-09-06 17:12
gotcha. 

> transaction.span_count.total of 0

I was thinking we'd be counting the spans even for unsampled transactions. If you're planing to set it to `0` for unsampled transactions, I would rather make it optional. `transaction.span_count.total=0` should indicate that we counted and there were no spans, not that we didn't count.

**Comment by roncohen** [comment] 2018-09-06 17:39
OK but could you still count them?, e.g. 

`this.total_spans++` [at the top here](https://github.com/elastic/apm-agent-nodejs/blob/abe9188675c9e638d9845dba3c4969cff43f11a4/lib/instrumentation/transaction.js#L109)

btw. off-topic and just an idea, but wouldn't it be better to always return a span, even when the transaction is not being sampled? to avoid allocating unnecessarily, it could just be the same dummy span, but it would save users a lot of if statements (`if (span) span.end()`). Also, the docs don't seem to mention that sampling affects the return value of `startSpan`. I think it would be nice to include something on that.

**Comment by Qard** [comment] 2018-09-06 18:08
It's better, from a performance perspective, to not have to allocate a span for every `startSpan` call. Counting attempts to build a span is possible for Node.js though. Hopefully it's not a significant change for other agents to be able to do that too. 🤔 

As for the docs, they _do_ mention that it will return `null` if there is no "active" transaction. That could perhaps be reworded to explain that "active" is referring to the sampling decision.

**Comment by roncohen** [comment] 2018-09-06 19:55
Sounds good @Qard. Let's move forward with it being required then 👍

**Comment by axw** [comment] 2018-09-07 02:52
> I was thinking we'd be counting the spans even for unsampled transactions. If you're planing to set it to 0 for unsampled transactions, I would rather make it optional. transaction.span_count.total=0 should indicate that we counted and there were no spans, not that we didn't count.

I thought the idea behind `transaction.span_count.total` was to give the UI an indication of how man spans were recorded. Is that not the case? For an unsampled transaction, there should be zero spans recorded, so counting them seems pointless (and causes some overhead due to locking or atomic ops).

The [Go agent currently](https://github.com/elastic/apm-agent-go/blob/v2/span.go#L43):
 - counts nothing for unsampled transactions
 - counts spans that were dropped due to max spans being reached
 - counts spans created (but not necessarily sent to the server)

The last point is to deal with spans that get dropped due to the agent being overloaded, causing events to be thrown away from the ring buffer, or otherwise when events are lost in transit (server goes down, beats queue fills up, etc.)

**Comment by roncohen** [comment] 2018-09-07 08:30
You are right.

I was thinking that it would be nicer to have the "real" count and the UI today filters out unsampled transactions when looking for a transaction to show you in the timeline, so it wouldn't be used. But I can see now that it would go against the purpose of that field. 

Lets set it to `0` for unsampled transactions.

**Comment by simitt** [comment] 2018-09-07 09:46
@elastic/apm-agent-devs after this discussion, I'd like to verify we are all on the same page now. 
Please tick off when you are fine with making `transaction.span_count.total` **required**, and set it to `0` in case of unsampled transactions.

* [ ] go 
* [ ] java
* [ ] nodejs
* [ ] python
* [ ] ruby 
* [ ] RUM

**Comment by Qard** [comment] 2018-09-07 20:16
Okay, so now I'm uncertain about the value when it _is_ sampled--should it be the number of _all_ spans, or the number of _reported_ spans?

ie: total - dropped == reported or total + dropped == all span count

**Comment by roncohen** [comment] 2018-09-10 08:01
@Qard good question. 
 
@watson from your answer, i take it you mean it should be:

> `transaction.span_count.total` + dropped == all span count

?


in other words, if spans are not created (or are dropped) due to the max span count being hit, those are not counted in the `transaction.span_count.total`? That's also how it's implemented in the Go agent AFAICT.

**Comment by axw** [comment] 2018-09-10 08:08
> in other words, if spans are not created (or are dropped) due to the max span count being hit, those are not counted in the transaction.span_count.total? That's also how it's implemented in the Go agent AFAICT.

In the Go agent there's two types of "dropped":
 - spans which are dropped because of the max span count
 - spans which are created, but later discarded (e.g. because the ring buffer was full)

Only the first type are counted in `span_count.dropped`. The second type are counted in `span_count.total`. Perhaps we should rename total to "started" or "created"? While I'm making suggestions, it would be nice if we could make the two counters have consistent naming. We now have `span_count.total` and `span_count.dropped.total`. Can we remove the ".total" from the latter?

**Comment by watson** [comment] 2018-09-10 08:47
@roncohen correct. And I like your suggestion

**Comment by simitt** [comment] 2018-09-10 14:03
I am fine with renaming on the Intake API, but renaming `span_count.dropped.total` to `span_count.dropped` in ES is not possible in a minor update, as the `type` would change from `object` to `int`.

**Comment by roncohen** [comment] 2018-09-10 14:34
@simitt OK. Would it be an option to use the opportunity now with intake v2 to change it just in the API and keep it the way it is in the Elasticsearch mapping? For 7.0 we can change the ES mapping, without requiring an update to the API.

**Comment by simitt** [comment] 2018-09-10 16:35
We can absolutely do that. Will add it. 

@elastic/apm-agent-devs the `v2` Intake API will then 
* require: `transaction.span_count.started`
* optional: `transaction.span_count.dropped`
* discard: `transaction.span_count.dropped.total`

**Comment by felixbarny** [comment] 2018-09-11 06:54
Is there a place which lists all the changes in v2? It would be also great to see which changes are already in the v2 branch and which changes are anticipated.

**Comment by roncohen** [comment] 2018-09-11 08:53
agree to use the v2 meta issue. I'm checking off boxes as things get merged.

**Closed** 2018-09-11 13:14 UTC
Labels: [zube]: In Review, discussion
