### ISSUE TITLE
Choose a suitable default port

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#64] opened 2017-08-17 13:53 UTC
Currently, our default port is `8080`. This is a port that is often used for local development of web services, so there's a high probability that we get a clash if people run `apm-server` locally with the default settings.

To optimize for the "getting started" scenario, we should choose a port that is

 * rarely used by other services
 * easy to remember

**Comment by beniwohli** [comment] 2017-08-17 13:54
My suggestion: `8200`. Elasticsearch's default port is `9200`, which makes `8200` easy to remember for people familiar with ES.

**Comment by crackerplace** [comment] 2017-08-20 10:28
@beernlinux I can work on this change.

Also,if we change [this](https://github.com/elastic/apm-server/blob/master/config/config.go#L14) to addr ,I believe it would be better ?

**Comment by ruflin** [comment] 2017-08-21 06:31
@crackerplace I can definitively see your point on why you would want to rename it to `address` as this is what is accepted in the end by the server in the Golang code. I would like to keep it `host` as I'm hoping people will past `hostname:port` which is AFAIK `host`. Also I'm probably biased because of ES also using `host`: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings :-) So happy to be convinced otherwise.

**Comment by ruflin** [comment] 2017-08-21 06:33
@beniwohli I like your suggestion of `8200`. Because it's starting with an `8` it somehow triggers my brain to think `http` and the other part is nicely close to ES.

**Comment by roncohen** [comment] 2017-08-21 07:46
I like 8200 as well. It looks like it's not a very occupied port, but it does look like we'd be sharing the port with GoToMyPC: http://support.citrixonline.com/en_us/meeting/all_files/G2M060010. I don't think that's a deal breaker. 

We might want to consider a different default port for when the apm-server is expecting SSL/TLS connections, similar to 80/443 for HTTP/S. AFAK it can be a bit difficult to debug issues caused by the server expecting a TLS connection but the agents using cleartext HTTP and vice-versa. Elasticsearch itself doesn't have separate ports for TLS/cleartext, which is probably a good indication that we shouldn't either - unless they regret that choice ;)

**Comment by crackerplace** [comment] 2017-08-21 20:31
@ruflin Separating host and port might be better instead of addr as addr looks more apt when connecting to external servers such as done in client libraries for redis etc.

I understand your reasoning as well and that sounds ok too.
Just a point,even [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings) has network.host and http.port.I don't think port is part of the host.

**Comment by ruflin** [comment] 2017-08-22 07:37
@crackerplace Good point about elasticsearch. I thought it can be define in one string but it seems you are right.

For our elasticsearch output we use `hosts`: https://github.com/elastic/apm-server/blob/master/apm-server.reference.yml#L143 But here the difference is that this can be an array and each host defined can have a different port. 

I somehow like that it can be defined in one string but I also see that lots of other places use `host` and `port`. 

@roncohen Any thoughts?

**Comment by jalvz** [comment] 2017-08-22 09:11
I am in a middle of server refactor right now, I will make `8200` default unless objections.

Separating host and port can be useful if you want to specify a different port for TLS, then you could also automatically redirect non secure connections over HTTPS.

**Comment by roncohen** [comment] 2017-08-22 12:13
@jalvz let's keep it separate, unless there's a specific reason to include that in a refactor?

**Comment by jalvz** [comment] 2017-08-22 12:20
i'm not touching that in the refactor either way (neither the port change, which i found it touches more things than initially thought, so scratch my last comment)
 
but with "keep separate" you mean "do separate"?  right now they are not separated.

**Comment by roncohen** [comment] 2017-08-22 12:22
"keep separate" as not in the same PR

**Comment by OmgImAlexis** [comment] 2017-08-23 05:10
Is the port for the nodejs client going to change too? I noticed it's currently setup to use 8081 which is the port [Sickrage](https://github.com/SickRage/SickRage)/[Medusa](https://github.com/pymedusa/medusa)/[Sickgear](https://github.com/SickGear/SickGear), etc. use

**Comment by watson** [comment] 2017-08-23 06:56
@OmgImAlexis I imagine you're talking about the following code:

https://github.com/elastic/apm-server/blob/045703bd6bf1cc18c4ad7d30df787d5c622f9c84/tests/agent/nodejs/app.js#L26-L28

This is only used for manual testing and is not run during normal operations. So I wouldn't personally worry too much about.

That being said, it's super easy in Node.js to simply find a random available port and listen on that. To modify the above code to do that, simply apply this patch:

```diff
-http.createServer(function (req, res) {
-  console.log(req.method, req.url)
-
-  res.writeHead(200, {'Content-Type': 'text/plain'})
-  res.end('Hello World\n')
-
-  apm.captureError(new Error('Ups, something broke'))
-
-}).listen(8081, function () {
-  console.log('server is listening on port 8081')
-})
+var server = http.createServer(function (req, res) {
+  console.log(req.method, req.url)
+
+  res.writeHead(200, {'Content-Type': 'text/plain'})
+  res.end('Hello World\n')
+
+  apm.captureError(new Error('Ups, something broke'))
+})
+
+server.listen(function () {
+  console.log('server is listening on port', server.address().port)
+})
```

This is the standard way in Node.js to make sure there's no port conflicts (though I'm not sure how easy it is to modify Docker to support this is).

**Comment by OmgImAlexis** [comment] 2017-08-23 07:13
@watson I'd suggest using [get-port](https://github.com/sindresorhus/get-port) with the host set to `0.0.0.0` for that.

**Comment by roncohen** [comment] 2017-08-23 09:53
OK, let's go with port `8200`. I'm opening a separate issue to discuss configuration naming.

**Comment by ruflin** [comment] 2017-08-23 09:53
@OmgImAlexis I personally quite like when I do manual testing that it's always on the same port as do it some other frameworks. Agree that we should probably change the default port from 8081 to something else to prevent conflicts. But lets move this to an other issue as it it's related to manual testing and no the apm server intake port.

**Comment by roncohen** [comment] 2017-08-23 11:34
Thanks for your input @OmgImAlexis and @crackerplace!
I'll close this issue now. Feel free to reopen if you feel there's more to discuss.

**Closed by roncohen** 2017-08-23 11:34 UTC
Labels: discuss
