### ISSUE TITLE
Revisit `error` fields and grouping logic

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1769] opened 2019-01-11 07:47 UTC
With Elastic agents covering more languages, questions around which attributes are supported and required by `error`, `error.exception` and `error.log` came up a couple of times. 
Some of these attributes are used for calculating the `grouping key`, see [calculation logic](https://github.com/elastic/apm-server/blob/master/model/error/event.go#L331).

This issue should be used to discuss requirements for errors and the grouping key calculation from the @elastic/apm-agent-devs and potential consequences for  the UI.

**Comment by axw** [comment] 2019-01-11 07:53
While looking into https://github.com/elastic/apm-agent-go/issues/423, I noticed that error.exception.module is not included in error grouping keys.

It's pretty common in Go to have an error type called simply "Error", with its package path used for context/discrimination. For example, in the standard library there's:

 - html/template.Error
 - go/scanner.Error
 - go/types.Error
 - regexp/syntax.Error
 - net/url.Error
 - net/textproto.Error
 - syscall/js.Error
 - os/exec.Error

I think we should include the module in the key too.

**Comment by jalvz** [comment] 2019-01-11 08:35
Changing the key means that the same error will show up in a different group after a version upgrade, which might annoy some users - so 7.0 would be an appropriate timeline for this.

**Comment by jalvz** [comment] 2019-01-15 12:07
Might be relevant https://github.com/elastic/apm/issues/11

**Comment by jalvz** [comment] 2019-08-23 16:02
If we are going to add `module` to the hash,  now is a good time so it goes out along with the cause list. Otherwise i think is better to just close this. Thoughts?

**Comment by graphaelli** [comment] 2019-08-23 16:56
I don't think there enough demand to warrant this change.  I'll add it to the 8.0 issue for consideration but support closing for now.

**Closed by graphaelli** 2019-08-23 16:56 UTC
Labels: [zube]: Backlog
