### ISSUE TITLE
Adapt apm package to package storage v2

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8491] opened 2022-06-27 11:34 UTC
Change the `apmpackage` to adhere to the [package storage v2](https://github.com/elastic/elastic-package/blob/main/docs/howto/use_package_storage_v2.md#use-package-storage-v2) rquirements and to upload signed packages. The job that [pushes the `apmpackage` to package-storage](https://github.com/elastic/apm-server/pull/7900) will need to be updated accordingly.

**Comment by mtojek** [comment] 2022-07-12 12:41
@simitt Could you please share a link/reference to your delivery pipeline? I may find some time to help you adjust it.

**Comment by simitt** [comment] 2022-07-12 14:14
@mtojek the apmpackage is developed in https://github.com/elastic/apm-server/tree/main/apmpackage and then [pushed](https://github.com/elastic/apm-server/pull/7900) to the package storage's snapshot branch.

**Comment by mtojek** [comment] 2022-07-12 14:29
Thanks @simitt. 

> Run in the CI manually, the packaging pipeline doesn't get triggered automatically on a PR basis, then the UI is the only way to test this out.

Do you know where is that pipeline? Does it support any dry-run for testing purposes? I assume that it's still triggered manually.

**Comment by simitt** [comment] 2022-07-13 11:52
After the PR was merged, the pipeline is triggered automatically:
> There are two actions that can trigger to publish a new apm package:
a. When identifying changes to the apmpackage after merging a PR to main or a release branch
b. When bumping the [version](https://github.com/elastic/apm-server/blob/master/cmd/version.go#L21) (usually happens after a stack release)

It generally appears to be part of the [package pipeline](https://apm-ci.elastic.co/job/apm-server/job/apm-server-package-mbp/job/main/). 
cc @v1v

**Comment by mtojek** [comment] 2022-07-13 15:14
I need to modify the pipeline code (Jenkinsfile, groovy) instead of modifying Makefile. The publishing pipeline has to call 2 pipelines:
- signing
- publishing

Similarly to https://github.com/elastic/integrations/pull/3658

**Comment by mtojek** [comment] 2022-07-18 12:53
I checked what the pipeline looks like and see a potential blocker. The current approach doesn't treat packages idempotently, which is obligatory as we will use the [publishing job](https://internal-ci.elastic.co/job/package_storage/job/publishing-job-remote/).

What we can is we can create the next revisions with prerelease tags. For example: `apm-8.3.0-beta1`, `apm-8.3.0-beta2`, or `apm-8.3.0-SNAPSHOT-1`, `apm-8.3.0-SNAPSHOT-2`, `apm-8.3.0-SNAPSHOT-3`, etc. You can find more valid options in this [test file](https://github.com/elastic/package-spec/blob/2c21cae1c7c6c270638fe747b75542dcebd9c0b3/code/go/internal/validator/semantic/validate_prerelease_test.go#L13).

For reference:
https://github.com/elastic/package-storage/commits/snapshot/packages/apm/8.3.0
https://github.com/elastic/package-storage/commits/snapshot/packages/apm/8.4.0

@simitt Please let me know what do you think.

**Comment by simitt** [comment] 2022-07-18 14:21
Kibana is bundling apm-server, currently from snapshot packages, and it uses the package from the same version. This was the reason we decided to simply override the same version during dev/FF phase (we do not do that on production). 

We will need to adapt the Kibana bundling to always bundle from the latest available prerelease tag and, if available, the release version. If I understand correctly, then this also means that we will need to release the release version already during the FF time (latest before the last BC is built) and have no way of adding bug fixes since the version cannot be overwritten. 

cc @joshdover and @axw

**Comment by mtojek** [comment] 2022-07-18 14:49
> Kibana is bundling apm-server, currently from snapshot packages, and it uses the package from the same version. This was the reason we decided to simply override the same version during dev/FF phase (we do not do that on production).

Yes, but in v2 there will be a flat space - no snapshot, staging, production. [docs](https://github.com/elastic/elastic-package/blob/main/docs/howto/use_package_storage_v2.md)

> We will need to adapt the Kibana bundling to always bundle from the latest available prerelease tag and, if available, the release version.

Yes, we can include timestamp in the semver prerelease it if it helps.

> If I understand correctly, then this also means that we will need to release the release version already during the FF time (latest before the last BC is built) and have no way of adding bug fixes since the version cannot be overwritten.

Hm.. maybe there is something I don't fully understand, but it should just mean to pick the right/latest revision. I'm not sure if there is any link between FF and BC.

**Comment by axw** [comment] 2022-07-19 01:04
>> If I understand correctly, then this also means that we will need to release the release version already during the FF time (latest before the last BC is built) and have no way of adding bug fixes since the version cannot be overwritten.
>
> I don't see a way around this with the immutable package direction we're going in. APM will need to use prerelease versions up until the final BC, or earlier.

This is going to be a problem. We need to be able to fix things between any BC and GA, and there's no knowing which BC will be the last, since blockers may be introduced at any time.

What we're after is a way to promote a package from prerelease to release without spinning a new package, and it sounds like that's not possible with package storage v2. Can that be rectified? Would it be possible to separate version tags from packages, similar to how Docker images are tagged? Then we would publish packages like:

- `8.4.0-<hash>-SNAPSHOT`. This would also be tagged as `8.4.0-SNAPSHOT`, replacing the previous tag.
- `8.4.0-<hash>`. This is a build candidate, and will be tagged as `8.4.0` on release day.

Similar to how Docker images have an immutable ID, the package itself would have an immutable identity, e.g. a content hash. The package itself would be immutable, but tags would not be.

**Comment by mtojek** [comment] 2022-07-19 06:47
> What we're after is a way to promote a package from prerelease to release without spinning a new package, and it sounds like that's not possible with package storage v2. Can that be rectified? Would it be possible to separate version tags from packages, similar to how Docker images are tagged?

Overriding packages is a dangerous operation and is the root cause of discrepancies as you never know which package is installed where. Anyway, is this habit only practiced by Docker? Frankly speaking, I haven't seen it in any other software release cycle.

When you publish a package, eventually it will land in the `artifacts/packages`:
https://package-storage.elastic.co/artifacts/packages/aws-1.16.4.zip

and some of its resources will be unpacked to `artifacts/static`, for example, an icon:
https://package-storage.elastic.co/artifacts/static/aws-1.16.4/img/logo_ebs.svg

As you can see, it's hard to maintain unpacked resources if a package can be replaceable, and we would like to play with hashes to identify .zip content.

Please also keep in mind that packages will be stored in a single flat space without promotions or removing packages. No snapshot, staging, and production as mentioned in this [document](https://github.com/elastic/elastic-package/blob/main/docs/howto/use_package_storage_v2.md).

@axw The new package distribution model works well with all packages except the APM, which is bundled with Kibana. Does it look like what you need is a map file that contains links between uploaded revisions and tags?

**Comment by mtojek** [comment] 2022-07-25 10:02
Summing up, I will try to modify [packaging.groovy](https://github.com/elastic/apm-server/blob/main/.ci/packaging.groovy) to call singing and publishing pipelines (cross-ci: `apm-ci` to `internal-ci`).

I will also adjust the [make build-package](https://github.com/elastic/apm-server/blob/cf8f0a616f94aadb00595c81ccdc2a61aa8ebd2d/Makefile#L193) to include a timestamp in the package version (prerelease).

I expect a few PRs for the Infra team to allow for cross-ci communication as we haven't integrated the apm-ci yet.

**Comment by mtojek** [comment] 2022-08-03 12:19
Status update:

The https://github.com/elastic/apm-server/pull/8717 is merged, so I guess that we can observe the [APM Server Package pipeline](https://apm-ci.elastic.co/job/apm-server/job/apm-server-package-mbp/job/main/).

BTW I don't see the apm 8.4.0 in [v1 production](https://github.com/elastic/package-storage/tree/production/packages/apm). Is it intended or forgotten?

**Comment by mtojek** [comment] 2022-08-03 12:44
Ok, the apm package was automatically published to Package Storage v2: https://epr-v2.ea-web.elastic.dev/search?prerelease=true&package=apm

@axw Is there anything else we should take care in terms of this issue or is it just https://github.com/elastic/kibana/issues/137759?

**Comment by axw** [comment] 2022-08-04 08:23
Thanks @mtojek, I believe all that's needed now is https://github.com/elastic/kibana/issues/137759. I'll close this as done.

**Closed by axw** 2022-08-04 08:23 UTC
Labels: enhancement
