### ISSUE TITLE
Defining apm-server.sampling.tail.interval causes throughput to cease

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#6638] opened 2021-11-16 17:46 UTC
**APM Server version** (`apm-server version`): 7.16.0-SNAPSHOT

<br class="Apple-interchange-newline">

**Description of the problem including expected versus actual behavior**:
The issue appears when `tail.interval` is introduced in the configuration yaml.  The documentation describes using a flush interval no greater than half the duration of `tail.ttl`. Following this instruction, or setting any other value to `tail.interval` results in all throughput of apm server to cease.

**Steps to reproduce**:
Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Running on cloud
 2. sending data w/ apm-integration-testing
 3. apply the following configuration:
```
apm-server:
  data_streams:
    enabled: true
  sampling:
    keep_unsampled: false
    tail:
      enabled: true
      ttl: 30s
      interval: 15s
      policies: 
        - sample_rate: 0.1 
```

**Comment by axw** [comment] 2022-01-18 09:45
I've also given it a shot with apm-integration-testing, using `./scripts/compose.py start 8.1.0 --with-opbeans-python`. I modified docker-compose.yml with the config specified in the description (excluding data_streams & keep_unsampled, which are now the defaults). I ran that for a while, and then changed sample_rate to 0.5 and ran that for a while.

Here's a screenshot of the number of sampled transaction docs in Discover.

![image](https://user-images.githubusercontent.com/843579/149911374-0dfecf2e-c3c6-4c3c-8f43-c3984db6c157.png)

With sample_rate=0.1, the number of docs is approximately 10% of the original. With sample_rate 0.5, it's approximately 50%.

Jumping over to the APM app, we can see the throughput is fairly steady regardless of the sampling rate:

![image](https://user-images.githubusercontent.com/843579/149911742-f34a528c-ef91-4013-a50c-81e75c48f3db.png)

There's a drop in the throughput chart at the end, because the final (i.e. current) bucket is incomplete.

All seems to be working as expected. Seeing as neither @stuartnelson3 nor I could reproduce it, I'm going to close this.

@bryce-b if you are still able to reproduce the issue, or provide more details that can enable us to do so, please reopen.

**Closed by axw** 2022-01-18 09:45 UTC
Labels: bug
