### ISSUE TITLE
span.duration.us is limited to 31 bit values (around 36 mins/2147 secs)

### ISSUE THREAD

**Issue by dgtrapeze** [elastic/apm-server#9780] opened 2022-12-10 13:49 UTC
**APM Server version** (`apm-server version`): 8.5.3

**Description of the problem including expected versus actual behavior**:

I have an application which uses opentelemetry library to collect trace information.  This is sent to a local opentelemetry collector which sends the trace information to elastic APM cloud.

I have a couple of operations within the application which can take a long time depending on the user's input.  I've noticed in kibana that sometimes these operations have a negative span.duration.us value and elastic APM really dislikes these negative values.

As the spans are generated by Otel, they are generated with a start and end date.  The duration calculation seems to be something done by the elastic APM ingestion system, as by the time the data gets to elastic APM it only has a start timestamp and duration.us

I originally thought the spans were being corrupted somehow and that the end time was being set to a time before the start time, but careful tracing of a long transaction showed this didn't happen - at least through to where the span left the opentelemetry collector and entered elastic APM.

I then noticed that I had no spans with a span.duration.us > 2147483647.  This is 2147 seconds or 35.7 mins.  The biggest spans in kibana stopped around this point.  So I now knew the data was being converted to a 32bit signed value at some point and my negative span.duration.us values were my long duration spans wrapped around.  

I checked the elastic APM otel processor to see what it did, but it seemed to convert the start+end time into a duration correctly using a time.Duration for it (which is 64 bit)

See https://github.com/elastic/apm-server/blob/1310b59ae3cfade0b6b909d4a7a6f8431553640e/internal/processor/otel/traces.go#L194

I then noticed this notice which talks about this field
https://www.elastic.co/guide/en/apm/guide/current/apm-breaking.html#_apm_server_now_emits_events_with_event_duration

So I read into this change and saw that it is using an ingest pipeline to copy the event.duration field (which is nanoseconds) to either the span/transation.duration.us field.  However it does this with

`ctx.get(ctx.processor.event).duration = ["us": (int)(durationNanos/1000)];`

See https://github.com/elastic/apm-server/blob/main/apmpackage/cmd/genpackage/pipelines.go#L160

This `int` looks remarkably like where the 32 bit truncation is occurring!

So I had a look for the ingest pipeline (which was called traces-apm-8.5.3 for me), manually changed the (int) to (long) - accepting the nasty warnings about changing a managed pipeline - and tried it out and... now my spans/transactions have the correct duration!

It does appear that the old code before this change also did cast the value to int
https://github.com/elastic/apm-server/pull/7261/commits/c47d1ffb597d2f28b8b6f4ee494e2df42856636f#diff-d8fa8642cc0172d5e5a9b7703d8288e7a8a6c14400071db413e56b126b8dbe05L148

but an int in go is probably 64 bits (in a 64 bit build) whereas an int in painless is only 32 bits (https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-types.html)

**Steps to reproduce**:
For me

1. Create a span that is 2148 seconds or more long

**Provide logs (if relevant)**:
Here is the span my test case generated as reported by the otel collector 

```
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Span #0
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Trace ID       : fcaa377d49b96366b4f4facb9e7c41a9
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Parent ID      : 76e4464a94373587
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: ID             : e7f49c039d9ff4a2
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Name           : inp.rostdfXX
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Kind           : SPAN_KIND_INTERNAL
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: Start time     : 2022-12-10 11:55:59.5911521 +0000 UTC
Dec 10 22:32:48 austricscentos7 otelcol-contrib[1395]: End time       : 2022-12-10 12:32:47.5122345 +0000 UTC
```

The duration should be around 2208 seconds

And here is the source document generated from it in elasticsearch showing the duration is the 2's compliment of this being -2087046214

```
  "_source": {
    "parent": {
      "id": "76e4464a94373587"
    },
    "agent": {
      "name": "opentelemetry/cpp",
      "version": "1.5.0"
    },
    "data_stream.namespace": "default",
    "processor": {
      "name": "transaction",
      "event": "span"
    },
    "data_stream.type": "traces",
    "observer": {
      "hostname": "44e0e5a8264e",
      "id": "7698c11a-60d0-4049-b1bb-afa74d8a04de",
      "type": "apm-server",
      "ephemeral_id": "949d5c2b-8e4f-4796-99a9-ed66eab43082",
      "version": "8.5.3"
    },
    "trace": {
      "id": "fcaa377d49b96366b4f4facb9e7c41a9"
    },
    "@timestamp": "2022-12-10T11:55:59.591Z",
    "ecs": {
      "version": "1.12.0"
    },
    "service": {
      "environment": "austricscentos7.mshome.net",
      "name": "ai"
    },
    "data_stream.dataset": "apm",
    "event": {
      "agent_id_status": "missing",
      "ingested": "2022-12-10T12:32:49Z",
      "outcome": "unknown"
    },
    "timestamp": {
      "us": 1670673359591152
    },
    "span": {
      "duration": {
        "us": -2087046214
      },
      "subtype": "internal",
      "name": "inp.rostdfXX",
      "id": "e7f49c039d9ff4a2",
      "type": "app"
    }
  },
```

**Comment by axw** [comment] 2022-12-12 02:31
@dgtrapeze thank you very much for the detailed issue, and for digging into the root cause. We'll get onto a fix.

**Comment by radukg** [comment] 2022-12-26 12:41
@axw do you have an estimated time / any release date when this can be fixed please?

**Comment by simitt** [comment] 2022-12-27 07:28
@radukg thanks again for the detailed report. After also verifiying that the index templates already define a `long` for both fields, I scheduled the task to get picked up. We will update here when we can say more which release it will be part of.

**Comment by kruskall** [comment] 2022-12-28 02:14
@dgtrapeze Thanks for the detailed report! It really helped with the investigation :+1:

**Closed** 2022-12-28 09:34 UTC
Labels: bug
