### ISSUE TITLE
Service view with OpenTelemetry traces report empty instance node names and miss dependencies

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#4972] opened 2021-03-18 21:26 UTC
**APM Server version** (`apm-server version`):

7.12-SNAPSHOT

```
apm-server version 7.12.0 (amd64), libbeat 7.12.0 [cc08062860651282026f807dc63ac3ab167a2da8 built 2021-03-16 10:00:17 +0000 UTC]
```

**Description of the problem including expected versus actual behavior**:

The APM Service view when displaying OpenTelemetry traces is 
* missing dependencies even though dependencies are found on the service map and looking at the distributed traces
* missing "time spend by span time" (we are already aware of this)
* missing the name of the instances

![image](https://user-images.githubusercontent.com/459691/111699824-e23b1100-8838-11eb-95d4-e2f63a058f3e.png)

![image](https://user-images.githubusercontent.com/459691/111700416-aa809900-8839-11eb-9b98-ee12515b4dfc.png)

**Steps to reproduce**:

Example application
https://github.com/cyrille-leclerc/my-shopping-cart/tree/open-telemetry

```
{
  "_index": "apm-7.12.0-transaction-000001",
  "_type": "_doc",
  "_id": "IS84R3gB9QfJzqEW8jr3",
  "_version": 1,
  "_score": null,
  "_source": {
    "parent": {
      "id": "fbdd0f9589210eaa"
    },
    "process": {
      "pid": 9387
    },
    "agent": {
      "name": "opentelemetry/java",
      "version": "1.0.1"
    },
    "source": {
      "ip": "127.0.0.1"
    },
    "processor": {
      "name": "transaction",
      "event": "transaction"
    },
    "url": {
      "path": "/api/orders",
      "original": "http://localhost:8080/api/orders",
      "scheme": "http",
      "port": 8080,
      "domain": "localhost",
      "full": "http://localhost:8080/api/orders"
    },
    "labels": {
      "process_runtime_description": "AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9",
      "thread_id": 36,
      "thread_name": "http-nio-8080-exec-1",
      "os_type": "DARWIN",
      "process_executable_path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home:bin:java",
      "process_runtime_name": "OpenJDK Runtime Environment",
      "os_description": "Mac OS X 10.16",
      "service_namespace": "com-shoppingcart",
      "process_command_line": "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home:bin:java -javaagent:./../.otel/opentelemetry-javaagent-all-1.0.1.jar -Dserver.port=8080",
      "process_runtime_version": "11.0.10+9",
      "telemetry_auto_version": "1.0.1"
    },
    "observer": {
      "hostname": "MacBook-Pro.localdomain",
      "id": "42495f8d-5c56-4a46-83ae-3ca5b5978fc1",
      "ephemeral_id": "dd9b3b77-af66-48dd-93ba-7fe1b0f897f0",
      "type": "apm-server",
      "version": "7.12.0",
      "version_major": 7
    },
    "trace": {
      "id": "a984e824347bf072951b46f4ba3de2b6"
    },
    "@timestamp": "2021-03-18T21:23:33.156Z",
    "ecs": {
      "version": "1.8.0"
    },
    "service": {
      "environment": "staging",
      "framework": {
        "name": "io.opentelemetry.javaagent.tomcat-7.0",
        "version": "1.0.1"
      },
      "name": "frontend",
      "language": {
        "name": "java"
      },
      "version": "1.0-SNAPSHOT"
    },
    "http": {
      "request": {
        "method": "POST",
        "socket": {
          "remote_address": "127.0.0.1:59398"
        }
      },
      "response": {
        "status_code": 201
      },
      "version": "1.1"
    },
    "client": {
      "ip": "127.0.0.1"
    },
    "event": {
      "ingested": "2021-03-18T21:23:37.838263Z",
      "outcome": "success"
    },
    "transaction": {
      "duration": {
        "us": 259566
      },
      "result": "HTTP 2xx",
      "name": "/api/orders",
      "id": "53283d9cc8c53c37",
      "type": "request",
      "sampled": true
    },
    "user_agent": {
      "original": "Java/11.0.10",
      "name": "Java",
      "device": {
        "name": "Spider"
      },
      "version": "0.10."
    },
    "timestamp": {
      "us": 1616102613156000
    }
  },
  "fields": {
    "event.ingested": [
      "2021-03-18T21:23:37.838Z"
    ],
    "@timestamp": [
      "2021-03-18T21:23:33.156Z"
    ]
  },
  "highlight": {
    "transaction.id": [
      "@kibana-highlighted-field@53283d9cc8c53c37@/kibana-highlighted-field@"
    ],
    "trace.id": [
      "@kibana-highlighted-field@a984e824347bf072951b46f4ba3de2b6@/kibana-highlighted-field@"
    ],
    "processor.event": [
      "@kibana-highlighted-field@transaction@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1616102613156
  ]
}
```

**Provide logs (if relevant)**:

**Comment by axw** [comment] 2021-03-22 04:40
> missing dependencies even though dependencies are found on the service map and looking at the distributed traces

I think I know what the issue is here -- we're not calculating service destination metrics for OpenTelemetry. I'll put up a fix for this soon.

> missing "time spend by span time" (we are already aware of this)

Yes, and to be clear we do not have any plans to resolve this.

> missing the name of the instances

If not otherwise specified, service node name is set to either the container ID or hostname. Neither of those are defined in the sample document you shared. I suppose you need to add something to the instrumentation.

**Comment by cyrille-leclerc** [comment] 2021-03-22 09:43
Thanks @axw .

I'll investigate on the instance identifier we can get.

**Closed** 2021-03-24 00:33 UTC
Labels: OpenTelemetry, [zube]: In Review, bug, test-plan, v7.13.0

**Comment by cyrille-leclerc** [comment] 2021-03-24 13:46
@axw is there a problem creating issues for the 2 pending problems surfaces in this ticket for better traceability?
These pending problems being:
* service instances report "(Empty)" name 
*  "Time spent by span type" is missing

**Comment by axw** [comment] 2021-03-25 01:16
@cyrille-leclerc I don't think those issues belong in apm-server.

> service instances report "(Empty)" name

As above, this appears to be an issue with your instrumentation. The service instance node name requires information that does not exist in the data your instrumented application is sending to apm-server.

> "Time spent by span type" is missing

This needs to be done at the instrumentation level. We could probably do this when bridging the OpenTelemetry API in our agents. Maybe open an issue in `elastic/apm`?

**Comment by axw** [comment] 2021-04-28 04:46
test plan tracked in https://github.com/elastic/apm-server/pull/4976
