### ISSUE TITLE
Add indices defaults in code

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1480] opened 2018-10-26 08:31 UTC
Index default configuration is currently only existing in `apm-server.yml`. For people upgrading, this is problematic. Since we now have a way to override beats configuration from APM Server code, we should align the defaults so that even without an `apm-server.yml`, the right defaults are used for indices.

**Comment by roncohen** [comment] 2018-10-26 08:45
marked it with v6.5 to show our hope that it will ship in 6.5, but not a blocker

**Comment by graphaelli** [comment] 2018-10-29 20:57
moved the other defaults to code in #1494, default indices are proving much trickier.  I think there's actually bug in here, working on a minimal case.

**Comment by graphaelli** [comment] 2018-10-30 12:34
After some discussion and go-ucfg schooling we've decided it's not a bug.  Unfortunately, there's also no current solution for providing a default list of indices that can be overridden by a config file / command line options.  In he strangest case, this is what happens right now:

code wants:

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  indices:
    - index: "apm-%{[beat.version]}-sourcemap-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "sourcemap"
```

user config says:

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  indices:
    - index: "apm-%{[beat.version]}-foo-%{+yyyy.MM.dd}"
```

actual config becomes:
```
output:
  elasticsearch:
    hosts:
    - localhost:9200
    indices:
    - index: apm-%{[beat.version]}-foo-%{+yyyy.MM.dd}
      when:
        contains:
          processor:
            event: sourcemap
```

**Comment by roncohen** [comment] 2018-10-30 12:46
Alright. We can’t just discard the code default if the user has anything
under “output.elasticsearch.indices” their config file?

**Comment by graphaelli** [comment] 2018-10-30 12:48
Not simply, no.  There are other cases in beats where arrays cause issues like this and we're brainstorming a nice general way to fix this.

**Comment by jalvz** [comment] 2019-01-17 14:58
@roncohen this is not going to happen for 7.0, do you still want to keep this around and investigate options (there are not many)?

**Comment by roncohen** [comment] 2019-01-17 17:38
I think it’s unfortunate that code defaults and apm-server.yml defaults deviate. I understand there's a limitation in beats that makes this impossible to fix at this time. I'm fine to close this.

I wonder if there's something we can do regarding documentation to highlight this behavior or we believe very few people will run into it?

**Comment by simitt** [comment] 2019-01-22 12:06
We might be able to set a default config from APM Server, in case my changes in https://github.com/elastic/beats/pull/10002 get merged.

**Closed** 2019-02-04 15:06 UTC
Labels: [zube]: In Review, breaking change, needs design
