### ISSUE TITLE
Implement context.request.url.full

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#410] opened 2017-12-19 12:44 UTC
We're introducing a `context.request.url.full` which should always be the full url for a transaction and for errors. There are very rare edge cases where a full url can not be assembled by the agent. In this case the field will be missing and the UI will not be able to show the URL. 

This needs to go in before 6.2.

**Comment by roncohen** [comment] 2017-12-19 12:44
cc @elastic/apm-agent-devs @elastic/apm-server

**Comment by beniwohli** [comment] 2017-12-19 12:51
This will replace `context.request.url.raw` in the Python agent. `raw` will only be used by the Node agent IIRC, and reflect the [`Request-URI`](https://tools.ietf.org/html/rfc2616#section-5.1) from the HTTP request.

**Comment by vanjacosic** [comment] 2017-12-19 13:11
Please ping the UI team once this has been implemented in APM Server and Python/Node.js 💡

**Comment by vanjacosic** [comment] 2018-01-03 13:11
@elastic/apm-agent-devs 

Agent folks, what is the status of your respective development processes? Please check in and update the checklist accordingly.

We on the UI team would like to implement this soon and test with all the different agent data. We'd prefer all the agents to be sending this data before Monday next week.

**Comment by beniwohli** [comment] 2018-01-03 13:15
@vanjacosic there's a checklist for this and all other changes in the 6.2 GA meta issue. I'd prefer to not have to keep multiple checklists up to date

**Comment by vanjacosic** [comment] 2018-01-03 13:25
@beniwohli Good point - we thought this was the master one since @roncohen created it and checked it off.

We've removed it now and will use 6.2 meta issue one as the master checklist going forward of course.

According to the meta checklist, Mikker and Beni are done. @watson / @Qard and @jahtalab, what's your status?

**Comment by watson** [comment] 2018-01-03 14:11
@vanjacosic I've linked to [an issue](https://github.com/elastic/apm-agent-nodejs/issues/106) on the Node agent repo in the 6.2 meta issue, but it might not be clear what that means. Here's our workflow:

- An unassigned issue means that we're aware of it
- If the issue is also in the "Scheduled" column in our [Scheduled](https://github.com/elastic/apm-agent-nodejs/projects/1) project it means that it's prioritized
- If the issue has a label in for form of `elastic-x.x` it means that we have detected that it needs to be ready before a certain Elastic version
- If the issue is assigned to a person it means that we're currently working on it
- We'll update the meta issue with a link to the PR once it's ready
- And check the box once it's merged

**Comment by jahtalab** [comment] 2018-01-03 16:08
@vanjacosic , `context.request` namespace does not apply to frontend, since a transaction on the frontend is related to a route change or page view but not a single request.

**Comment by vanjacosic** [comment] 2018-01-03 16:13
@watson Roger that, thanks for the explanation

@jahtalab Ah, good to know. I will remove "frontend" from the master checklist then. 

Or before I do that I should ask:  does it apply to errors on the frontend?

**Comment by jahtalab** [comment] 2018-01-03 16:25
@vanjacosic , it doesn't apply to errors either.

**Comment by simitt** [comment] 2018-01-13 15:44
Afaik this was implemented in the server+agents, therefore I'll close this.

**Closed by simitt** 2018-01-13 15:44 UTC
Labels: v6.2
